"""add vote abuse telemetry

Revision ID: 6253c63eb43f
Revises: ae69b7f5a392
Create Date: 2026-09-29 22:21:05.615053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6253c63eb43f'
down_revision: Union[str, Sequence[str], None] = 'ae69b7f5a392'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_scores_submission_judge'), 'scores', type_='unique')
    op.add_column('votes', sa.Column('fingerprint', sa.String(length=128), nullable=True))
    op.alter_column('votes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_votes_fingerprint'), 'votes', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_votes_ip_address'), 'votes', ['ip_address'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_votes_ip_address'), table_name='votes')
    op.drop_index(op.f('ix_votes_fingerprint'), table_name='votes')
    op.alter_column('votes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('votes', 'fingerprint')
    op.create_unique_constraint(op.f('uq_scores_submission_judge'), 'scores', ['submission_id', 'judge_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
