"""add scorecard integrity hash

Revision ID: 76ad204a3958
Revises: 239a688f9bbf
Create Date: 2026-09-29 22:39:56.746975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76ad204a3958'
down_revision: Union[str, Sequence[str], None] = '239a688f9bbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scores', sa.Column('scorecard_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_scores_scorecard_hash'), 'scores', ['scorecard_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scores_scorecard_hash'), table_name='scores')
    op.drop_column('scores', 'scorecard_hash')
    # ### end Alembic commands ###
